version: "2"
services:
  api:
    container_name: docker-app-api
    image: app/api
    build: ./api
    command: node ./bin/www
    ports:
      - "3001:3001"
    environment:
      MONGODB_URI: mongodb://mongo:27017
      PORT: 3001
    volumes:
      - .:/usr/src/ask-apiko-api
    links:
      - mongo
  mongo:
   container_name: mongo
   image: mongo
   ports:
      - "27018:27017"
